---
title: "R Notebook"
output: github_document
---
```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, results = "hide", fig.align = "center",
                      fig.height = 3.5, fig.width = 3.5)
```

## Introduction 

## Load Libraries & Prepare Workspace
```{r loadLibraries, results = "hide"}
# data manipulation
library(tidyverse, quietly = T)
library(stringr, quietly = T)
library(forcats, quietly = T)

# machine learning tools
library(PRROC, quietly = T)
library(caret, quietly = T)
library(xgboost, quietly = T)

# ggplot2 theme
source("../R/ggplotTheme.R")
theme_set(coolTheme)

# other functions
source("../R/prepareData.R")
source("../R/utilityFunctions.R")

# for reproducibility
set.seed(0847532)
```

## Evaluation of Model Performance on Isolate Spectra in Library
```{r singles}
testList <- readRDS("../temp/testDatList.rds")
testdmatList <- prepareData(testList, orgLabs = c("Ab", "Kp"))

mods <- readRDS("../temp/finalModels.rds")

formatResults <- function(model, dataList) {
    results <- as.data.frame(predict(model, dataList$dat, reshape = T))
    names(results) <- levels(unique(dataList$encoding)[[1]])
    
    results <- results %>%
        mutate(truth = dataList$encoding[[1]],
               negVsAll = pos + other,
               posVsAll = neg + other,
               speciesVsAll = pos + neg,
               pred = ifelse(neg > pos & neg > other, "neg", NA),
               pred = ifelse(pos > neg & pos > other, "pos", pred),
               pred = ifelse(other > neg & other > pos, "other", pred))
    
    return(results)
}

```

### Acinetobacter baumannii
```{r AbSingleSpec, results='markup'}
abMod <- xgb.load(mods$Ab)
abRes <- formatResults(abMod, testdmatList$Ab)

abCm <- confusionMatrix(data = abRes$pred, reference = abRes$truth, positive = "pos")
abCm

# Ab PR curves
abPosPR <- pr.curve(abRes$pos[abRes$truth == "pos"], 
                    abRes$pos[abRes$truth != "pos"], curve = T)

abNegPR <- pr.curve(abRes$neg[abRes$truth == "neg"], 
                    abRes$neg[abRes$truth != "neg"], curve = T)

abSpeciesPR <- pr.curve(abRes$speciesVsAll[abRes$truth != "other"], 
                        abRes$speciesVsAll[abRes$truth ==  "other"], curve = T)

# Ab ROC curves
abPosROC <- roc.curve(abRes$pos[abRes$truth == "pos"], 
                    abRes$pos[abRes$truth != "pos"], curve = T)

abNegROC <- roc.curve(abRes$neg[abRes$truth == "neg"], 
                    abRes$neg[abRes$truth != "neg"], curve = T)

abSpeciesROC <- roc.curve(abRes$speciesVsAll[abRes$truth != "other"], 
                        abRes$speciesVsAll[abRes$truth ==  "other"], curve = T)
```

### Klebsiella pneumoniae
```{r KpSingleSpec, results="markup"}
kpMod <- xgb.load(mods$Kp)
kpRes <- formatResults(kpMod, testdmatList$Kp)

kpCm <- confusionMatrix(data = kpRes$pred, reference = kpRes$truth, positive = "pos")
kpCm

# Kp PR curves
kpPosPR <- pr.curve(kpRes$pos[kpRes$truth == "pos"], 
                    kpRes$pos[kpRes$truth != "pos"], curve = T)

kpNegPR <- pr.curve(kpRes$neg[kpRes$truth == "neg"], 
                    kpRes$neg[kpRes$truth != "neg"], curve = T)

kpSpeciesPR <- pr.curve(kpRes$speciesVsAll[kpRes$truth != "other"], 
                        kpRes$speciesVsAll[kpRes$truth ==  "other"], curve = T)

# Kp ROC curves
kpPosROC <- roc.curve(kpRes$pos[kpRes$truth == "pos"], 
                    kpRes$pos[kpRes$truth != "pos"], curve = T)

kpNegROC <- roc.curve(kpRes$neg[kpRes$truth == "neg"], 
                    kpRes$neg[kpRes$truth != "neg"], curve = T)

kpSpeciesROC <- roc.curve(kpRes$speciesVsAll[kpRes$truth != "other"], 
                        kpRes$speciesVsAll[kpRes$truth ==  "other"], curve = T)
```

### Plot PR and ROC Curves
#### Acinetobacter PR  & ROC Curves
```{r, AbPR, results="hold", fig.show="hold"}
# PR
prnames <- c("Recall", "Precision", "threshold")
prAb <- as.tibble(rbind(abPosPR$curve, abNegPR$curve, abSpeciesPR$curve))
names(prAb) <- prnames

labsAb <- c(paste0("Resistant, AUC = ", sigRound(abPosPR$auc.integral, 3)),
            paste0("Susceptible, AUC = ", sigRound(abNegPR$auc.integral, 3)),
            paste0("Species, AUC = ", sigRound(abSpeciesPR$auc.integral, 3)))

AbPrCurve <- prAb %>%
    mutate(cond = c(rep(labsAb[1], nrow(abPosPR$curve)),
                    rep(labsAb[2], nrow(abNegPR$curve)),
                    rep(labsAb[3], nrow(abSpeciesPR$curve))),
           cond = fct_rev(fct_relevel(as.factor(cond), labsAb))) %>%
    ggplot(aes(x = Recall, y = Precision, color = cond)) +
    geom_path(size = 1)  +
    coord_equal() +
    theme(legend.position = c(0.05,0.05),
          legend.justification = c(0,0),
          legend.title = element_blank()) +
    ggtitle(expression(italic("A. baummannii")))

AbPrCurve
ggsave("../results/AbPrCurve.png", width = 3.5, height = 3.5)

# ROC
rocnames <- c("1 - Specificity", "Sensitivity", "threshold")
rocAb <- as.tibble(rbind(abPosROC$curve, abNegROC$curve, abSpeciesROC$curve))
names(rocAb) <- rocnames

roclabsAb <- c(paste0("Resistant, AUC = ", sigRound(abPosROC$auc, 3)),
               paste0("Susceptible, AUC = ", sigRound(abNegROC$auc, 3)),
               paste0("Species, AUC = ", sigRound(abSpeciesROC$auc, 3)))

AbRocCurve <- rocAb %>%
    mutate(cond = c(rep(roclabsAb[1], nrow(abPosROC$curve)),
                    rep(roclabsAb[2], nrow(abNegROC$curve)),
                    rep(roclabsAb[3], nrow(abSpeciesROC$curve))),
           cond = fct_rev(fct_relevel(as.factor(cond), roclabsAb))) %>%
    ggplot(aes(x = `1 - Specificity`, y = Sensitivity, color = cond)) +
    geom_path(size = 1)  +
    coord_equal() +
    theme(legend.position = c(0.95,0.05),
          legend.justification = c(1,0),
          legend.title = element_blank()) +
    ggtitle(expression(italic("A. baummannii")))

AbRocCurve
ggsave("../results/AbRocCurve.png", width = 3.5, height = 3.5)


```

#### Klebsiella pneumoniae PR  & ROC Curves
```{r, KpPR, results = "hold", fig.show = "hold"}
# PR
prnames <- c("Recall", "Precision", "threshold")
prKp <- as.tibble(rbind(kpPosPR$curve, kpNegPR$curve, kpSpeciesPR$curve))
names(prKp) <- prnames

labsKp <- c(paste0("Resistant, AUC = ", sigRound(kpPosPR$auc.integral, 3)),
            paste0("Susceptible, AUC = ", sigRound(kpNegPR$auc.integral, 3)),
            paste0("Species, AUC = ", sigRound(kpSpeciesPR$auc.integral, 3)))

KpPrCurve <- prKp %>%
    mutate(cond = c(rep(labsKp[1], nrow(kpPosPR$curve)),
                    rep(labsKp[2], nrow(kpNegPR$curve)),
                    rep(labsKp[3], nrow(kpSpeciesPR$curve))),
           cond = fct_rev(fct_relevel(as.factor(cond), labsKp))) %>%
    ggplot(aes(x = Recall, y = Precision, color = cond)) +
    geom_path(size = 1)  +
    coord_equal() +
    theme(legend.position = c(0.05,0.05),
          legend.justification = c(0,0),
          legend.title = element_blank()) +
    ggtitle(expression(italic("K. pneumoniae")))

KpPrCurve

ggsave("../results/KpPrCurve.png", width = 3.5, height = 3.5)

# ROC
rocnames <- c("1 - Specificity", "Sensitivity", "threshold")
rocKp <- as.tibble(rbind(kpPosROC$curve, kpNegROC$curve, kpSpeciesROC$curve))
names(rocKp) <- rocnames

roclabsKp <- c(paste0("Resistant,AUC = ", sigRound(kpPosROC$auc, 3)),
               paste0("Susceptible,AUC = ", sigRound(kpNegROC$auc, 3)),
               paste0("Species, AUC = ", sigRound(kpSpeciesROC$auc, 3)))

KpRocCurve <- rocKp %>%
    mutate(cond = c(rep(roclabsKp[1], nrow(kpPosROC$curve)),
                    rep(roclabsKp[2], nrow(kpNegROC$curve)),
                    rep(roclabsKp[3], nrow(kpSpeciesROC$curve))),
           cond = fct_rev(fct_relevel(as.factor(cond), roclabsKp))) %>%
    ggplot(aes(x = `1 - Specificity`, y = Sensitivity, color = cond)) +
    geom_path(size = 1) +
    coord_equal() + 
    theme(legend.position = c(0.95,0.05),
          legend.justification = c(1,0),
          legend.title = element_blank())  +
    ggtitle(expression(italic("K. pneumoniae")))

KpRocCurve
ggsave("../results/KpRocCurve.png", width = 3.5, height = 3.5)

# save plots for later use:
save(AbPrCurve, AbRocCurve, KpPrCurve, KpRocCurve, file = "../temp/curves.rda")
```

## Variable Importance
```{r varImp, results = "hold", fig.show = "hold", fig.width = 4}
vImpAb <- xgb.importance(colnames(testdmatList$Ab$dat), model = abMod) %>%
    mutate(org = "Ab")

vImpKp <- xgb.importance(colnames(testdmatList$Kp$dat), model = kpMod) %>%
    mutate(org = "Kp")

basePeaks <- c("1912.5448", # Ab
               "1841.4497")
resPeaks <- c("2036.4927", # Ab
              "1957.1088", # Kp
              "1973.1961")

vImp <- vImpAb %>%
    full_join(vImpKp) %>%
    mutate(featureMz = as.factor(str_replace(Feature, "mz", "")),
           featureMz = fct_reorder(featureMz, Gain, .desc = T),
           color = ifelse(featureMz %in% basePeaks, "Known Base Lipid A Structure", NA),
           color = ifelse(featureMz %in% resPeaks, "Known Resistance Lipid A Structure", color)) %>%
    group_by(org) %>%
    arrange(desc(Gain)) %>%
    filter(Gain >= Gain[20])

# Acinetobacter
vImpAbPlot <- vImp %>%
    filter(org == "Ab") %>%
    ggplot(aes(x = featureMz, y = Gain, ymax = Gain, ymin = 0)) +
    geom_linerange(size = 1) +
    geom_point(size = 2, aes(color = color)) +
    xlab(expression(paste("Feature (", italic("m/z"), ")"))) +
    scale_color_discrete(breaks = c("Known Base Lipid A Structure", "Known Resistance Lipid A Structure")) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
          legend.position = c(0.95, 0.95),
          legend.justification = c(1, 1),
          legend.title = element_blank()) +
    ggtitle(expression(italic("A. baummannii")))

vImpAbPlot
ggsave("../results/vImpAbPlot.png", height = 3, width = 4)

# Klebsiella
vImpKpPlot <- vImp %>%
    filter(org == "Kp") %>%
    ggplot(aes(x = featureMz, y = Gain, ymax = Gain, ymin = 0)) +
    geom_linerange(size = 1) +
    geom_point(size = 2, aes(color = color)) +
    xlab(expression(paste("Feature (", italic("m/z"), ")"))) +
    scale_color_discrete(breaks = c("Known Base Lipid A Structure", "Known Resistance Lipid A Structure")) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
          legend.position = c(0.95, 0.95),
          legend.justification = c(1, 1),
          legend.title = element_blank()) +
    ggtitle(expression(italic("K. pneumoniae")))

vImpKpPlot
ggsave("../results/vImpKpPlot.png", height = 3, width = 4)

# save for later
save(vImpAbPlot, vImpKpPlot, file = "../temp/vImpPlots.rda")

```

## Determine How Spectra Are Misclassified
```{r misclassified}
abCmTable <- as.tibble(abCm$table) %>% mutate(species = "Ab")
kpCmTable <- as.tibble(kpCm$table) %>% mutate(species = "Kp")

cmTable <- abCmTable %>% full_join(kpCmTable)

```

