---
title: "Strategy Illustrations"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r loadLibraries, results = "hide", echo = FALSE}
library(tidyverse, quietly = T)
library(MALDIquant, quietly = T)
library(MALDIquantForeign, quietly = T)
library(caret, quietly = T)
library(PRROC, quietly = T)
library(stringr, quietly = T)
library(forcats, quietly = T)

# ggplot2 theme
source("../R/ggplotTheme.R")
theme_set(coolTheme)

source("../R/preProcessSpec.R")
source("../R/extract.R")

set.seed(6554)

```

# Feature Creation

```{r}
features <- readRDS("../temp/features.rds")
features <- filter(features, response == "Ab")

featFiles <- c(list.files("../data/fullLib/Acinetobacter baumannii - res", 
                    full.names = T, 
                    pattern = "mzXML$",
                    recursive = T)[1],
                list.files("../data/fullLib/Acinetobacter baumannii - sen", 
                    full.names = T, 
                    pattern = "mzXML$",
                    recursive = T)[1])

spec <- preProcessSpec(featFiles, hws = 80)

specDat <- map_df(spec, extractSpectra) %>%
    mutate(class = str_replace(type, "Acinetobacter", "A."),
           class = str_replace(class, " - res", ", Colistin-Resistant"),
           class = str_replace(class, " - sen", ", Colistin-Susceptible"),
           relInt = relInt * 100)


featurePlot <- specDat %>%
    ggplot(aes(x = mz, y = relInt)) +
    geom_segment(data = features, aes(x = mz, xend = mz, y = -1, yend = -10), 
                 color = "steelblue") +
    geom_line() +
    facet_wrap(~ class, nrow = 2) +
    xlab("m/z") +
    ylab("Relative Intensity")

featurePlot 
ggsave("../results/featureSelect_1.png", width = 7.5, height = 5)

selectedMz <- features$mz[which.min(abs(features$mz - 2033))] 

maxDf <- specDat %>%
    filter(mz > selectedMz - 1.5,
           mz < selectedMz + 1.5) %>%
    group_by(class) %>%
    summarize(mz = mz[relInt == max(relInt)],
              relInt = max(relInt))

featurePlotZoom1 <- specDat %>%
    filter(str_detect(class, "Resistant")) %>%
    ggplot(aes(x = mz, y = relInt)) +
    annotate("rect", xmin = selectedMz - 1.5, xmax = selectedMz + 1.5, 
             ymin = -Inf, ymax = Inf, alpha = 0.1, fill = "steelBlue", color = "steelBlue") +
    geom_line() +
    geom_vline(data = features,  aes(xintercept = mz), color = "steelBlue", linetype = "dashed") +
    geom_point(data = filter(maxDf, str_detect(class, "Resistant")), 
               aes(x = mz, y = relInt + 1.5), color = "black", shape = 8, size = 1.5) + 
    xlim(selectedMz + c(-5, 5)) +
    ylim(c(0, 35)) +
    theme(axis.title = element_blank())

featurePlotZoom1

ggsave("../results/featureSelect_2_1.png",  width = 1.75, height = 1.25)


# Zoom 2
featurePlotZoom2 <- specDat %>%
    filter(str_detect(class, "Susceptible")) %>%
    ggplot(aes(x = mz, y = relInt)) +
    annotate("rect", xmin = selectedMz - 1.5, xmax = selectedMz + 1.5, 
             ymin = -Inf, ymax = Inf, alpha = 0.1, fill = "steelBlue", color = "steelBlue") +
    geom_line() +
    geom_vline(data = features,  aes(xintercept = mz), color = "steelBlue", linetype = "dashed") +
    geom_point(data = filter(maxDf, str_detect(class, "Susceptible")), 
               aes(x = mz, y = relInt + 1.5), color = "black", shape = 8, size = 1.5) + 
    xlim(selectedMz + c(-5, 5)) +
    ylim(c(0, 35)) +
    theme(axis.title = element_blank())

featurePlotZoom2

ggsave("../results/featureSelect_2_2.png",  width = 1.75, height = 1.25)

maxDf %>%
    ggplot(aes(x = class, y = relInt)) +
    geom_bar(stat = "identity") +
    coolTheme +
    theme(axis.title.x = element_blank()) +
    ylab("Feature Intensity")

ggsave("../results/featureSelect_3.png", width = 2, height = 1.5)
```


# Real vs Simulated Complex Spectra

```{r}

colRanges <- tibble(minMz = c(1300, 1440, 1810),
                    maxMz = c(1430, 1640, 2100),
                    lab = c("S. aureus",
                            "P. aeruginosa",
                            "K. pneumoniae"))

shortenName <- function(origName) {
  paste0(str_match(origName, "^."),
         ". ",
         str_match(origName, " ([^ ]+)")[ , 2])
}


# import and plot individual spec
soi <- c("S aureus NRS384 1 10282016",
         "P aeruginosa BE399 4 10282016",
         "K pneumoniae TBE818 5 10132016")
files <- list.files("../data/fullLib", 
                    full.names = T, 
                    pattern = "mzXML$",
                    recursive = T)

files <- map_chr(soi, ~files[str_detect(files, .)])

spec <- preProcessSpec(files, hws = 80)

specDat <- map_df(spec, extractSpectra) 

spPlot <- specDat %>%
  mutate(spc = shortenName(type),
         relInt = relInt * 100,
         mzRange = ifelse(mz > colRanges$minMz[1] & mz < colRanges$maxMz[1] & spc == "S. aureus", 
                          colRanges$lab[1], NA),
         mzRange = ifelse(mz > colRanges$minMz[2] & mz < colRanges$maxMz[2] & spc == "P. aeruginosa", 
                          colRanges$lab[2], mzRange),
         mzRange = ifelse(mz > colRanges$minMz[3] & mz < colRanges$maxMz[3] & spc == "K. pneumoniae", 
                          colRanges$lab[3], mzRange)) 


spPlot %>%
  ggplot(aes(x = as.numeric(mz), y = relInt)) +
  geom_line(size = 0.5) +
  geom_line(data = spPlot[!is.na(spPlot$mzRange), ], aes(color = mzRange), size = 0.5) +
  coolTheme +
  theme(legend.position = "none") +
  labs(x = "m/z",
       y = "Relative Intensity") +
  facet_wrap(~ spc, ncol = 1)

ggsave("../results/individualSpec.png", width = 3.5, height = 4)


 # Make combined Spectrum ----------------------------------------------------------------------
cmb <- specDat %>% 
  mutate(spec_id = "spec_1") %>%
  group_by(spec_id ,id, type) %>%
  do(massSpecObj = createMassSpectrum(mass = .$mz, intensity = .$relInt, 
                                      metaData = list(file = "a"))) %>%
  group_by(spec_id) %>%
  do(massSpecObj = averageMassSpectra(.$massSpecObj, method = "sum"))


cmbSpec <- extractSpectra(cmb$massSpecObj[[1]])

cmbSpecNorm <-  cmbSpec %>%
  mutate(relInt = relInt / max(relInt) * 100,
         type = "combined",
         id = "combined") %>%
  group_by(mz) %>%
  mutate(mzRange = ifelse(mz > colRanges$minMz[1] & mz < colRanges$maxMz[1], 
                          colRanges$lab[1], NA),
         mzRange = ifelse(mz > colRanges$minMz[2] & mz < colRanges$maxMz[2], 
                          colRanges$lab[2], mzRange),
         mzRange = ifelse(mz > colRanges$minMz[3] & mz < colRanges$maxMz[3], 
                          colRanges$lab[3], mzRange))

cmbSpecNorm %>%
  ggplot(aes(x = as.numeric(mz), y = relInt)) +
  geom_line(size = 0.5) +
  geom_line(data = cmbSpecNorm[!is.na(cmbSpecNorm$mzRange), ], aes(color = mzRange), size = 0.5) +
  theme(legend.position = "none") +
  labs(title = "Simulated",
       x = "m/z",
       y = "Relative Intensity")

ggsave("../results/inSilicoSpec.png", width = 3.5, height = 2.25)

# Import and plot experimental mixed spectrum --------------------------------------------------------
mixFile <- list.files("../data/mixSpec", pattern = ".mzXML", full.names = T)[1]
origSpec <- preProcessSpec(mixFile, hws = 80)
origSpecDat <- map_df(origSpec, extractSpectra)

origSpecNorm <- origSpecDat %>%
  group_by(mz) %>%
  summarize(relInt = sum(relInt)) %>%
  ungroup() %>%
  mutate(relInt = relInt / max(relInt) * 100,
         type = "combined",
         id = "combined") %>%
  mutate(mzRange = ifelse(mz > colRanges$minMz[1] & mz < colRanges$maxMz[1], 
                          colRanges$lab[1], NA),
         mzRange = ifelse(mz > colRanges$minMz[2] & mz < colRanges$maxMz[2], 
                          colRanges$lab[2], mzRange),
         mzRange = ifelse(mz > colRanges$minMz[3] & mz < colRanges$maxMz[3], 
                          colRanges$lab[3], mzRange))

origSpecNorm %>%
  ggplot(aes(x = as.numeric(mz), y = relInt)) +
  geom_line(size = 0.5) +
  geom_line(data = origSpecNorm[!is.na(origSpecNorm$mzRange), ], aes(color = mzRange), size = 0.5) +
  coolTheme +
  theme(legend.position = "none") +
  labs(title = "Experimental",
       x = "m/z",
       y = "Relative Intensity")

ggsave("../results/experimentalSpec.png", width = 3.5, height = 2.25)


# random weights -------------------------------------------------------------------------
specDat2 <- specDat %>% mutate(spec_id = "Spec_2")
specDat3 <- specDat %>% mutate(spec_id = "Spec_3")
specDat4 <- specDat %>% mutate(spec_id = "Spec_4")

specCombo <- specDat2 %>% full_join(specDat3) %>% full_join(specDat4)

idInfo <- tibble(id = as.factor(c("Spec_2", "Spec_3", "Spec_4")),
                 labs = as.factor(c("0.63 * Kp + 0.59 * Pa + 1.00 * Sa",
                          "1.00 * Kp + 0.18 * Pa + 0.35 * Sa",
                          "0.92 * Kp + 1.00 * Pa + 0.13 * Sa")))

set.seed(13476)
specCombo <- specCombo %>% 
  group_by(spec_id ,id, type) %>%
  mutate(coeff = runif(1, 0.1, 1)) %>%
  group_by(spec_id) %>%
  mutate(trueCoeff = coeff / max(coeff))

coeffs <- specCombo %>%
  group_by(spec_id, type) %>%
  summarise(coeff = trueCoeff[1])

cmb2 <- specCombo %>%
  group_by(spec_id, id, type) %>% 
  mutate(relInt = relInt * coeff) %>% 
  do(massSpecObj = createMassSpectrum(mass = .$mz, intensity = .$relInt, 
                                      metaData = 
                                        list(file =paste0("/combined/", .$spec_id[[1]], ".mzXML")))) %>%
  group_by(spec_id) %>%
  do(massSpecObj = averageMassSpectra(.$massSpecObj, method = "sum"))

specCmb2 <- map_df(cmb2$massSpecObj, extractSpectra)

specCmb2 <-  specCmb2 %>%
  mutate(mzRange = ifelse(mz > colRanges$minMz[1] & mz < colRanges$maxMz[1], 
                          colRanges$lab[1], NA),
         mzRange = ifelse(mz > colRanges$minMz[2] & mz < colRanges$maxMz[2], 
                          colRanges$lab[2], mzRange),
         mzRange = ifelse(mz > colRanges$minMz[3] & mz < colRanges$maxMz[3], 
                          colRanges$lab[3], mzRange)) %>%
  left_join(idInfo) %>%
  mutate(relInt = relInt * 100)

specCmb2 %>%
  ggplot(aes(x = as.numeric(mz), y = relInt)) +
  geom_line(size = 0.5) +
  geom_line(data = specCmb2[!is.na(specCmb2$mzRange), ], aes(color = mzRange), size = 0.5) +
  coolTheme +
  theme(legend.position = "none") +
  labs(x = "m/z",
       y = "Relative Intensity") +
  facet_wrap(~ labs, ncol = 1) 

ggsave("../results/randomMixedSpec.png", width = 4, height = 4)


```

# Increasing Spectral Complexity

```{r}
# Illustration of increasing complexity
files <- list.files("../data/fullLib", 
                    full.names = T, 
                    pattern = "mzXML$",
                    recursive = T)

specInfo <- tibble(fname = files) %>%
  mutate(type = str_match(fname, "([^\\^/]+)[\\/][^\\^/]+mzXML$")[ , 2],
         id = str_match(fname, "([^\\^/]+).mzXML$")[ , 2],
         species = str_match(type, "^[^ ]+ [^ ]+"))

speciesSelect <- specInfo %>%
  group_by(species) %>%
  summarize(num = length(id)) %>%
  sample_n(size = 40)

selected <- speciesSelect %>%
  left_join(specInfo) %>%
  group_by(species) %>%
  sample_n(size = 1) %>%
  ungroup() %>%
  mutate(coeff = runif(40, 0, 1))

files <- files[files %in% selected$fname]

spec <- preProcessSpec(files, hws = 80)

specDat <- map_df(spec, extractSpectra)

specFull <- selected %>%
  select(id, coeff) %>%
  left_join(specDat) %>%
  mutate(relInt = relInt * coeff)

cmb <- map_df(c(1, 2, 5, 10, 20, 40), function(x) {
  sel <- selected$id[1:x]
  dat <- filter(specFull, id %in% sel)
  
  cmb <- dat %>%
    mutate(spec_id = as.factor(paste0("spec_", x))) %>%
    group_by(spec_id, id, type) %>%
    do(massSpecObj = createMassSpectrum(mass = .$mz, intensity = .$relInt, 
                                        metaData = 
                                          list(file = paste0("/cmb/", .$spec_id[1], ".mzXML")))) %>%
    group_by(spec_id) %>%
    do(massSpecObj = averageMassSpectra(.$massSpecObj, method = "sum"))
  
    return(cmb)
})

cmbDat <- map_df(cmb$massSpecObj, extractSpectra)

cmbDat %>%
  mutate(relInt = relInt * 100,
         lab = paste0(gsub("spec_", "", id), " Species"),
         lab = fct_reorder(lab, as.numeric(str_match(lab, "^([^ ]+) ")[ , 2]))) %>%
  ggplot(aes(x = as.numeric(mz), y = relInt)) +
  geom_line(size = 0.5) +
  coolTheme +
  theme(legend.position = "none") +
  labs(x = "m/z",
       y = "Relative Intensity") +
  facet_wrap(~ lab, ncol = 2)
```


