---
title: "Make Miscellaneous Figures"
author: "William E Fondrie"
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE,
                      results = "hide",
                      cache = T,
                      cache.lazy = F)
```

## Load Libraries and  Prepare Workspace
```{r loadLibraries, results = "hide"}
# data manipulation
suppressMessages(library(tidyverse, quietly = T))
library(stringr, quietly = T)
library(forcats, quietly = T)
library(devtools, quietly = T)

# handling MALDI spectra
library(MALDIquant, quietly = T)
library(MALDIquantForeign, quietly = T)

# ggplot2 theme
source("../R/ggplotTheme.R")
theme_set(coolTheme)

set.seed(09813734)

# import helper functions
source("../R/preProcessSpec.R")
source("../R/extract.R")
source("../R/utilityFunctions.R")
```

## Load Data
```{r loadData, results='hide'}
files <- list.files("../data/fullLib", 
                     full.names = T, 
                     pattern = "mzXML$",
                     recursive = T)

specInfo <- tibble(fname = files) %>%
    mutate(type = str_match(fname, "([^\\^/]+)[\\/][^\\^/]+mzXML$")[ , 2],
           id = str_match(fname, "([^\\^/]+).mzXML$")[ , 2],
           species = str_match(type, "^[^ ]+ [^ ]+"),
           Ab = ifelse(str_detect(type, "Acinetobacter baumannii - res"), "pos", "other"),
           Kp = ifelse(str_detect(type, "Klebsiella pneumoniae - res"), "pos", "other"),
           Ab = as.factor(ifelse(str_detect(type, "Acinetobacter baumannii - sen"), "neg", Ab)),
           Kp = as.factor(ifelse(str_detect(type, "Klebsiella pneumoniae - sen"), "neg", Kp)))

summary(specInfo)

features <- readRDS("../temp/features.RDS")

specList <- unlist(map(files, preProcessSpec, hws = 80)) # Same preprocessing

spec <- map_df(specList, extractSpectra)

feattbl <- spec %>%
  group_by(id) %>%
  do(extractFeatures(., featureVec = unique(features$mz), tol = 1.5))
```

## Plot of Resistance Peaks and Their Variation
```{r peaks}
# Ab
abFeat <- feattbl$feat[feattbl$mz == nom2feat(2036, feattbl$mz)]
# Kp
kpFeat <- c(feattbl$feat[feattbl$mz == nom2feat(1956, feattbl$mz)],
            feattbl$feat[feattbl$mz == nom2feat(1972, feattbl$mz)])

feattbl %>%
  filter((str_detect(type, "Klebsiella pneumoniae") & feat %in% kpFeat) |
           (str_detect(type, "Acinetobacter baumannii") & feat %in% abFeat)) %>%
  mutate(res = ifelse(str_detect(type, "res"), "Colistin\nResistant", "Colistin\nSusceptible"),
         species = ifelse(str_detect(type, "Acineto"), "A. baumannii", "K. pneumoniae"),
         feat = str_replace(feat, "mz", "Feature m/z ")) %>%
  ggplot(aes(y = relInt, x = res)) +
  geom_jitter(alpha = 0.5, size = 1) +
  stat_summary(fun.ymax = median, fun.ymin = median, 
               fun.y = median, color = ggColors(3)[3], geom="crossbar") +
  facet_wrap(~species + feat) +
  ylab("Relative Intensity") +
  theme(axis.title.x = element_blank())

ggsave("../results/resPeaks.pdf", width = 105, height = 50, unit = "mm", useDingbats = F)
  

```

## Mass Accuracy Plot 
```{r massAccuracyPlots}
AbSpec <- nom2feat(2033, feattbl$mz)[1]

feattblWide <- spec %>%
  group_by(id) %>%
  do(extractFeatures(., featureVec = AbSpec, tol = 1.5))


specSelect <- c("Acinetobacter baumannii - res",
                "Salmonella minnesota")

feattblWide %>%
    filter(type %in% specSelect) %>%
    mutate(species = ifelse(str_detect(type, "Acinetobacter baumannii - res"),
                             "Resistant\nA. baumannii", "S. minnesota"),
           species = as.factor(species)) %>%
    mutate(feat = str_replace(feat, "mz", "Feature m/z ")) %>%
    ggplot(aes(y = real_mz, x = species)) +
    geom_dotplot(aes(color = fct_rev(species), 
                     fill = fct_rev(species)), 
                 binaxis = "y", stackdir = "center", dotsize = 0.75) +
    geom_boxplot(outlier.shape = NA, fill = NA) +
    geom_hline(yintercept = AbSpec, 
               size = 0.5, linetype = "dashed") +
    ylim(c(AbSpec - 1.5, AbSpec + 1.5)) +
    ylab(expression("Extracted"~italic("m/z"))) +
    theme(legend.position = "none",
          axis.title.y = element_blank()) + 
    coord_flip()
    
ggsave("../results/peakExtraction.pdf", width = 70, height = 50, unit = "mm", useDingbats = F)


twoSpecSel <- c("Ab ACAT PM3850 2 05182016",
                "Salmonella minnesota R595 TBE1121 3 06242016")

twoSpec <- spec %>%
    filter(id %in% twoSpecSel) %>%
    mutate(type = str_replace(type, "Acinetobacter", "Resistant A."),
           type = str_replace(type, " - res", ""),
           type = str_replace(type, "Salmonella", "S."))


twoSpec %>%
    ggplot(aes(x = mz, y = relInt)) +
    geom_line() +
    facet_wrap(~ type, ncol = 1) +
    xlab(expression(italic("m/z"))) +
    ylab("Relative Intensity")

ggsave("../results/minnesotaSpec.pdf", width = 140, height = 100, unit = "mm", useDingbats = F)


twoSpec %>%
    filter(mz >= AbSpec - 5 & mz <= AbSpec + 5) %>%
    group_by(type) %>%
    mutate(relInt = relInt / max(relInt)) %>%
    ungroup() %>%
    mutate(type = str_replace(type, "Resistant ", "Resistant\n")) %>%
    ggplot(aes(x = mz, y = relInt, color = fct_rev(type))) +
    annotate("rect", xmin = AbSpec - 1.5, xmax = AbSpec + 1.5, 
             ymin = -Inf, ymax = Inf, alpha = 1, fill = "lightgrey", color = "lightgrey") +
    geom_vline(xintercept = AbSpec, size = 0.5, linetype = "dashed") +
    geom_vline(xintercept = c(AbSpec - 1.5, AbSpec + 1.5), size = 0.5) +
    geom_line() +
    xlab(expression(italic("m/z"))) +
    ylab("Relative Intensity") +
    theme(legend.title = element_blank(),
          legend.margin = margin(l = -0.5, r = -0.2, unit = "lines"),
          legend.key.size = unit(0.5, "lines"))

ggsave("../results/minnesotaZoom.pdf", width = 70, height = 50, unit = "mm", useDingbats = F)

```


## Plot of the Isolate Dataset
```{r libraryDistro}
specInfo %>% 
  group_by(species) %>%
  mutate(num = length(id)) %>%
  ungroup() %>%
  mutate(`Colistin\nResistant` = 
           ifelse(Ab == "pos" | Kp == "pos", "Colistin-Resistant", NA),
         `Colistin\nResistant` = 
           ifelse(Ab == "neg" | Kp == "neg", "Colistin-Susceptible", `Colistin\nResistant`),
         `Colistin\nResistant` = fct_rev(`Colistin\nResistant`),
         species = fct_lump(species, 20),
         species = fct_reorder(species, num)) %>%
  ggplot(aes(x = species, fill = `Colistin\nResistant`)) +
  geom_bar(color = "black", width = 0.75) +
  ylab("Number of Mass Spectra") +
  scale_fill_discrete(name = NULL, breaks = c("Colistin-Resistant","Colistin-Susceptible")) +
  coord_flip() +
  coolTheme +
  theme(legend.position = c(0.95, 0.25),
        legend.justification = c(1,0),
        axis.title.y = element_blank(),
        legend.background = element_rect(color = "black"),
        legend.key.size = unit(0.75, "lines"),
        legend.title = element_blank())

ggsave("../results/library.pdf", height = 125, width = 105, unit = "mm", useDingbats = F)


specInfo %>% 
  group_by(species) %>%
  mutate(num = length(id)) %>%
  ungroup() %>%
  mutate(`Colistin\nResistant` = 
           ifelse(Ab == "pos" | Kp == "pos", "Colistin-Resistant", NA),
         `Colistin\nResistant` = 
           ifelse(Ab == "neg" | Kp == "neg", "Colistin-Susceptible", `Colistin\nResistant`),
         `Colistin\nResistant` = fct_rev(`Colistin\nResistant`),
         species = fct_lump(species, 10),
         species = fct_reorder(species, num)) %>%
  ggplot(aes(x = species, fill = `Colistin\nResistant`)) +
  geom_bar(color = "black", width = 0.75) +
  ylab("Number of Mass Spectra") +
  scale_fill_discrete(name = NULL, breaks = c("Colistin-Resistant","Colistin-Susceptible")) +
  coord_flip() +
  theme(legend.position = c(0.95, 0.25),
        legend.justification = c(1,0),
        axis.title.y = element_blank(),
        legend.background = element_rect(color = "black"),
        legend.text = element_text(size = 10),
        legend.key.size = unit(0.75, "lines"),
        legend.title = element_blank(),
        axis.text = element_text(size = 10),
        axis.title.x = element_text(size = 10))

ggsave("../results/librarySmall.pdf", height = 100, width = 150, unit = "mm", useDingbats = F)

summary(specInfo$species)
length(unique(specInfo$species))
```

## Session Info
```{r sessionInfo, results = "markup"}
session_info()
```