---
title: "R Notebook"
output: github_document
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Introduction

# Prepare Workspace
```{r loadLibraries, results = "hide"}
# data manipulation
library(tidyverse, quietly = T)
library(stringr, quietly = T)
library(forcats, quietly = T)

# handling MALDI spectra
library(MALDIquant, quietly = T)
library(MALDIquantForeign, quietly = T)

# machine learning
library(caret, quietly = T)
library(PRROC, quietly = T)
library(xgboost, quietly = T)

# import helper functions
source("../R/preProcessSpec.R")
source("../R/extract.R")

# for reproducibility
set.seed(1832939)
```


# Partition Data
```{r getFileInfo}
files <- list.files("../data/fullLib", 
                    full.names = T, 
                    pattern = "mzXML$",
                    recursive = T)
#files <- sample(files, 50) # uncomment for testing

specInfo <- tibble(fname = files) %>%
    mutate(type = str_match(fname, "([^\\^/]+)[\\/][^\\^/]+mzXML$")[ , 2],
           id = str_match(fname, "([^\\^/]+).mzXML$")[ , 2],
           Ab = ifelse(str_detect(type, "Acinetobacter baumannii - res"), "pos", "other"),
           Kp = ifelse(str_detect(type, "Klebsiella pneumoniae - res"), "pos", "other"),
           Ab = as.factor(ifelse(str_detect(type, "Acinetobacter baumannii - sen"), "neg", Ab)),
           Kp = as.factor(ifelse(str_detect(type, "Klebsiella pneumoniae - sen"), "neg", Kp)))

trainIdx <- list(Ab = list(idx = createDataPartition(specInfo$Ab, p = 0.6, list = F),
                           regex = "Acinetobacter baumannii - res"),
                 Kp = list(idx = createDataPartition(specInfo$Kp, p = 0.6, list = F),
                           regex = "Klebsiella pneumoniae - res"))

```

# Select Features from Training Data
```{r determineFeatures, cache = TRUE}
determineFeatures <- function(trainList, n = 20) {
    # Preprocess spectra
    spec <- preProcessSpec(files[trainList$idx], hws = 80)
    multiSpecIdx <- map_lgl(spec, ~ metaData(.)$num > 1)
    spec <- spec[!multiSpecIdx]

    # Detect peaks
    peaks <- detectPeaks(spec, halfWindowSize = 80, SNR = 5)
    peaks <- binPeaks(peaks, tolerance = 0.5)
    
    # extract peaks
    peakDat <- extractPeaks(peaks, spec)
    
    # extract features
    features <- peakDat %>%
        mutate(sel = str_detect(type, trainList$regex)) %>%
        filter(sel) %>%
        group_by(sel, mz) %>%
        summarize(relInt = sum(relInt)) %>%
        group_by(sel) %>%
        mutate(relInt = relInt / max(relInt)) %>%
        arrange(desc(relInt)) %>%
        filter(relInt >= relInt[n]) %>%
        arrange(desc(mz))
    
    return(features)
}

featureList <- map(trainIdx, determineFeatures)
trainIdx$Ab$features <- unique(featureList$Ab$mz)
trainIdx$Kp$features <- unique(featureList$Kp$mz)


features <- tibble(response = names(featureList), featList = featureList) %>%
    unnest() %>%
    select(response, mz)

features <- unique(features)
saveRDS(features, file = "../temp/features.RDS")
```

# Extract features from Spectra
```{r extractFeatures, cache = TRUE}
createFeatureTbl <- function(trainList, mzTol, testSet = F) {
    idx <- if(testSet) -trainList$idx else trainList$idx
    suffix <- if(testSet) "_test" else "_train"
    suffix2 <- if(str_detect(trainList$regex, "Acineto")) "_Ab" else "_Kp"
    
    # Preprocess spectra
    spec <- preProcessSpec(files[idx], hws = 80)
    multiSpecIdx <- map_lgl(spec, ~ metaData(.)$num > 1)
    spec <- spec[!multiSpecIdx]
    
    # extract spectra 
    spectbl <- map_df(spec, extractSpectra) %>% 
      mutate(type = as.factor(type), id = as.factor(id))
    
    # extract specified features
    feattbl <- spectbl %>%
      group_by(id) %>%
      do(extractFeatures(., featureVec = trainList$features, tol = mzTol))
    
    saveRDS(feattbl, file = paste0("../temp/featureInfo", suffix2, suffix))
    
    mlFeat <- feattbl %>%
      select(id, type, feat, relInt) %>%
      group_by(id) %>%
      mutate(relInt = relInt / max(relInt)) %>%
      ungroup() %>%
      spread(key = feat, value = relInt, fill = 0) %>%
      mutate(Ab = ifelse(str_detect(type, "i - r"), "pos", "other"),
             Kp = ifelse(str_detect(type, "e - r"), "pos", "other"),
             Ab = as.factor(ifelse(str_detect(type, "i - s"), "neg", Ab)),
             Kp = as.factor(ifelse(str_detect(type, "e - s"), "neg", Kp)))
    
    return(mlFeat)
}

trainDatList <- map(trainIdx, createFeatureTbl, 
                    mzTol = 1,
                    testSet = F)

saveRDS(trainDatList, "../temp/trainDatList.rds")
```

# Train the XGBoost tree models 
## Prepare the Data
```{r prepareData}
prepareData <- function(trainDatList, orgLabs) {
    dmlist <- map(orgLabs, function(o){
        dat <- trainDatList[[o]]
        
        y <- dat[ , o] %>% mutate(encoding = as.numeric(.[[o]]) - 1)
        
        x <- as.matrix(select(dat, starts_with("mz")))
        
        return(list(encoding = y,
                    dat = xgb.DMatrix(x, label = y$encoding)))
    })
    
    names(dmlist) <- orgLabs
    return(dmlist)
    
} 

dmatList <- prepareData(trainDatList, orgLabs = c("Ab", "Kp"))
saveRDS(dmatList, "../temp/dmatList.rds")

```

## Rough Model Tuning by grid search
```{r xgboost_tune1, results = "hide"}
paramGrid <- expand.grid(max_depth = seq(1, 10, by = 1),
                              min_child_weight = 1:10,
                              gamma = c(0, 0.01, 0.05, 0.1, 0.15))

paramGrid$id <- 1:nrow(paramGrid)


xgbParams <- list(objective = "multi:softprob",
                  booster = "gbtree",
                  num_class = 3)

optimizeXgbParams <- function(params, data, eta) {
    tune <- xgb.cv(params = xgbParams,
                   data = data,
                   nrounds = 20000,
                   eta = eta,
                   nfold = 10,
                   early_stopping_rounds = 100,
                   max_depth = params$max_depth,
                   min_child_weight = params$min_child_weight,
                   gamma = params$gamma,
                   metrics = "mlogloss")
    
    bst <- as.data.frame(tune$evaluation_log) %>%
        filter(test_mlogloss_mean == min(test_mlogloss_mean))
    
    return(cbind(params, bst))
}

paramRes <- map_df(dmatList, function(org) {
    paramGrid %>%
        group_by(id) %>%
        do(optimizeXgbParams(., org$dat, 0.3))
}, .id = "org")


paramRes %>%
    filter(org == "Kp") %>%
    ggplot(aes(y = test_mlogloss_mean, x = min_child_weight, color = as.factor(max_depth), group = as.factor(max_depth))) + 
    geom_point() +
    geom_line() +
    facet_grid(gamma ~ .)

bstParams <- paramRes %>%
    group_by(org) %>%
    filter(test_mlogloss_mean == min(test_mlogloss_mean))

```

## Model Refinement
```{r refinement, results = "none"}

finalParams <- bstParams %>%
                group_by(org) %>%
                do(optimizeXgbParams(., dmatList[[.$org]]$dat, 0.01))


```

## Final Model
```{r finalModel, results = "none"}
orgs <- c("Ab", "Kp")

mods <- map(orgs, function(org){
    
    params <- finalParams[finalParams$org == org, ]
    
    xgb.train(params = xgbParams,
              data = dmatList[[org]]$dat,
              nrounds = params$iter,
              max_depth = params$max_depth,
              min_child_weight = params$min_child_weight,
              gamma = params$gamma,
              eta = 0.01)
})

names(mods) <- orgs
saveRDS(mods, "../temp/finalModels.rds")
```